name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Playwright dependencies
      - name: Install Playwright dependencies
        run: npx playwright install-deps

      # Step 5: Install browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # Step 6: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules

      - name: Create .lambdatest file
        run: |
           echo "{ \"user\": \"varunkumarb\", \"key\": \"GhGShOYHz1jODWE9qDvkJK4nPDR3n2lc0gNp9VknalhwtUineG\" }" > .lambdatest

      - name: Start LambdaTest Tunnel
        run: node your-tunnel-start-script.js
